version: "3"

services:
  cinemaccsdb:
    restart: always
    image: mariadb
    container_name: cinemaccsdb
    volumes:
      - cinemaccs_mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env

  cinemaccsapi:
    restart: always
    container_name: cinemaccsapi
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/django
      - cinemaccs_media:/media
    ports:
      - "8000:8000"
    depends_on:
      - cinemaccsdb
    env_file:
      - .env

  cinemaccsfront:
    restart: always
    container_name: cinemaccsfront
    build: ./front
    # command: yarn start
    volumes:
      - ./front/public:/app/public
      - ./front/src:/app/src
      - ./front/package.json:/app/package.json
      - ./front/yarn.lock:/app/yarn.lock
      - ./front/tsconfig.json:/app/tsconfig.json
      - ./front/Dockerfile:/app/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - cinemaccsdb
      - cinemaccsapi
    env_file:
      - .env

  cinemaccsdagster:
    restart: always
    container_name: cinemaccsdagster
    build: ./scripts
    volumes:
      - ./scripts:/dagster
    ports:
      - "3010:3000"
    depends_on:
      - cinemaccsapi
    env_file:
      - .env

volumes:
  cinemaccs_mariadb_data:
  cinemaccs_media: