# Generated by Django 4.1.4 on 2022-12-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaccs_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='theater',
            name='accessibilityDescription',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='address1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='address2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='allowOnlineVoucherValidation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='allowPrintAtHomeBookings',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='cinemaNationalId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='complexSlug',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='currencyCode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='displaySofaSeats',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='insertDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='internal_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='isGiftStore',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='parkingInfo',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='publicTransport',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='timeZoneId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='theater',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
