# Generated by Django 4.1.4 on 2022-12-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaccs_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=300, null=True)),
                ('logo', models.ImageField(max_length=255, null=True, upload_to='pictures/logo')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicap_familly', models.CharField(choices=[('PMR', 'Mobility')], default='PMR', max_length=5)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('duration', models.CharField(max_length=300, null=True)),
                ('allocineId', models.CharField(max_length=10, null=True)),
                ('isanId', models.CharField(max_length=50, null=True)),
                ('poster', models.ImageField(max_length=255, null=True, upload_to='pictures/movies')),
                ('releaseDate', models.DateTimeField(null=True)),
                ('synopsis', models.CharField(max_length=500, null=True)),
                ('director', models.CharField(max_length=300, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internalRoomId', models.CharField(max_length=20, null=True)),
                ('seats', models.IntegerField(null=True)),
                ('accessPoint', models.CharField(choices=[('bottom', 'bottom'), ('middle', 'middle'), ('top', 'top')], max_length=10, null=True)),
                ('wheelchairSpaces', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('accessibilityDescription', models.CharField(max_length=1000, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.CharField(max_length=300, null=True)),
                ('picture', models.ImageField(max_length=255, null=True, upload_to='pictures/rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.IntegerField(null=True)),
                ('movieId', models.IntegerField(null=True)),
                ('internalSessionId', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('accessibilityDescription', models.CharField(max_length=1000, null=True)),
                ('sessionTime', models.DateTimeField(null=True)),
                ('language', models.CharField(choices=[('VO', 'VO'), ('VF', 'VF')], default='VF', max_length=5)),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TheaterPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theaterId', models.CharField(max_length=300, null=True)),
                ('picture', models.ImageField(max_length=255, null=True, upload_to='pictures/theaters')),
            ],
        ),
        migrations.AddField(
            model_name='theater',
            name='accessibilityDescription',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='address1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='address2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='allowOnlineVoucherValidation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='allowPrintAtHomeBookings',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='cinemaNationalId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='complexSlug',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='currencyCode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='displaySofaSeats',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='entryDescription',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='internalId',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='isGiftStore',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='modifiedDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='parkingInfo',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='popcornDescription',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='publicTransport',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='sanitaryDescription',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='timeZoneId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='theater',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='theater',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
