# Generated by Django 4.1.4 on 2022-12-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaccs_project', '0003_rename_insertdate_theater_createdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicap_familly', models.CharField(choices=[('PMR', 'Mobility')], default='PMR', max_length=5)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('duration', models.CharField(max_length=300, null=True)),
                ('allocine_id', models.CharField(max_length=10, null=True)),
                ('isan_id', models.CharField(max_length=50, null=True)),
                ('poster', models.FileField(null=True, upload_to='')),
                ('releaste_date', models.DateTimeField(null=True)),
                ('synopsis', models.CharField(max_length=500, null=True)),
                ('director', models.CharField(max_length=300, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='theater',
            old_name='createDate',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='theater',
            old_name='modifyDate',
            new_name='modifiedDate',
        ),
    ]
